### ISSUE TITLE
ModuleNotFoundError: No module named 'readability_classifier'

### ISSUE THREAD

**Issue by BaumiCoder** [LuKrO2011/code-readability-classifier#8]
I try to use the implementation from the [predict](https://github.com/LuKrO2011/code-readability-classifier/tree/predict) branch.
I follow the steps at the [Installation section](https://github.com/LuKrO2011/code-readability-classifier/tree/predict?tab=readme-ov-file#Installation). Then I try to call the main.py like described:
```bash
(readability-classifier-predict-py3.11) user@host /path/where/I/clone/the/repository python src/readability_classifier/main.py PREDICT --model tests/res/models/towards.h5 --input tests/res/code_snippets/towards.java
Traceback (most recent call last):
File "/path/where/I/clone/the/repository/src/readability_classifier/main.py", line 9, in <module>
    from readability_classifier.model_runner_interface import ModelRunnerInterface
ModuleNotFoundError: No module named 'readability_classifier'
```
I also tried with another working directory (instead of `/path/where/I/clone/the/repository`, `/path/where/I/clone/the/repository/src` or `/path/where/I/clone/the/repository/src/readability_classifier`), with the path to the main.py adjusted properly. The error stays the same.

My environment:
- Operating system: Linux Mint 21.3 MATE
- Python - I try with two version:
     - Python 3.11.0rc1 from apt-get
     - Python 3.11.5 self build and called like this:
       ```bash
       poetry shell
       ../Python-3.11.5/python src/readability_classifier/main.py PREDICT --model tests/res/models/towards.h5 --input tests/res/code_snippets/towards.java
       ```

Could there be any misconfiguration on my site? Is it a bug in the project?

**Comment by BaumiCoder** [comment]
In the main branch is a slightly different error:
```
Traceback (most recent call last):
  File "/path/to/repo/code-readability-classifier/src/readability_classifier/main.py", line 10, in <module>
    from readability_classifier.encoders.dataset_encoder import DatasetEncoder
  File "/path/to/repo/code-readability-classifier/src/readability_classifier/encoders/dataset_encoder.py", line 6, in <module>
    from readability_classifier.encoders.bert_encoder import BertEncoder
  File "/path/to/repo/code-readability-classifier/src/readability_classifier/encoders/bert_encoder.py", line 7, in <module>
    from readability_classifier.encoders.dataset_utils import (
  File "/path/to/repo/code-readability-classifier/src/readability_classifier/encoders/dataset_utils.py", line 10, in <module>
    from src.readability_classifier.utils.config import DEFAULT_MODEL_BATCH_SIZE
ModuleNotFoundError: No module named 'src'
```
My actual workaround is to replace `src.readability_classifier` with `readability_classifier` in all `py` files that work for both branches. This allows me to run it with `poetry shell` and `poetry run`, but it still not work with `poetry env use` and PyCharm also mark the imports as errors.  (Both of course based on the changes from #11)

The `src` seems to be not necessary, with [this line](https://github.com/LuKrO2011/code-readability-classifier/blob/2012c9c283f83b22fd3ea3f3eb8a5ad067c96b1b/pyproject.toml#L79) in the pyproject.toml, see [stackoverflow](https://stackoverflow.com/a/50156706). There also should be no `__init__.py` in the `src` (and `tests`) directory. This should work also for the tests, but they normally use a `test_` prefix for directories or files, to avoid naming conflicts (e.g., [here](https://www.geeksforgeeks.org/typical-directory-structure-for-running-tests-using-unittest-in-python/)).

For the `src` layout there is a [documentation](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/), which states that an [editable installation](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) is necessary. I tried this, after I set up the project with `poetry install`. The `pip install --editable .` triggers a download of all dependencies (again). After this PyCharm does not show any errors anymore at the imports. `poetry env use`  still not work, but switching to the environment without poetry (on Linux `source venv/bin/activate`) works.

**Comment by LuKrO2011** [comment]
I am currently investigating the issues. As soon as I can confirm the procedure described, I will merge the corresponding pull requests and/or update the branches accordingly.

**Comment by LuKrO2011** [comment]
I am currently applying changes to the "gpu" branch. Once everything works, I will merge it into master.

First, the imports were inconsistent. Sometimes it was with “src.” at the beginning, and sometimes without. I changed this by adding “src.” to each import statement.

After that, I was able to reproduce the error (thanks to a tip from @BaumiCoder) by not using a shell within the IDE, but a separate shell. For me, the solution was to run the following command in the project directory:
`export PYTHONPATH=“readability-classifier”:$PYTHONPATH`

Can you try this and see if it fixes the problem for you?

Regarding the “src” folder itself:
I would like to keep the “src.” folder to avoid conflicts with the similarly structured “test” folder. 
The “src” folder is actually not necessary, but rather a design decision: https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
For me, neither Windows nor Ubuntu required an editable installation.
However, if this problem persists, I will consider removing the “src” folder and thus switching to the flat layout.

Regarding the dependencies:
I am currently working on updating the dependencies for both a pip install, and a poetry install variant with GPU support.

**Comment by BaumiCoder** [comment]
When I use `poetry shell` or `poetry run`, it works with doing `export PYTHONPATH=“readability-classifier”:$PYTHONPATH` before (or in the poetry shell). This solution is actual only mentioned for [Using Pip](https://github.com/LuKrO2011/code-readability-classifier/tree/gpu?tab=readme-ov-file#using-pip). It should be also mentioned for poetry if there is no way to set this path with the `pyproject.toml`.

**Comment by LuKrO2011** [comment]
I added the instruction to the improved README on the GPU branch.

**Comment by BaumiCoder** [comment]
> I added the instruction to the improved README on the GPU branch.

I only find [this](https://github.com/LuKrO2011/code-readability-classifier/blob/gpu/README.adoc?plain=1#L95) about `PYTHONPATH` in the README there. This is in the `Using Pip` section, which suggest that it is not necessary for `Using Poetry`.

**Comment by LuKrO2011** [comment]
I clarified this in the Readme.
